### ISSUE TITLE
Will it support yuzu in the future?

### ISSUE THREAD

**Issue by HighPingTek** [Monkbreh/MHGU-HD-Project#2]
Is it possible to convert this mod to yuzu? I wish I had the PlayStation buttons and 60fps together

**Comment by Monkbreh** [comment]
The mod will crash the game if you try to load it in yuzu, naturally it should work but that's up to the dev team to make it happen. Yuzu doesn't seem to support a lot of mods beyond simple cheat codes.

**Comment by HighPingTek** [comment]
> The mod will crash the game if you try to load it in yuzu, naturally it should work but that's up to the dev team to make it happen. Yuzu doesn't seem to support a lot of mods beyond simple cheat codes.

do you have a timeline to support other languages for alternate buttons?

**Comment by Monkbreh** [comment]
Yes, support for more languages will be there

**Comment by Squall-Leonhart** [comment]
should be fixed in https://github.com/yuzu-emu/yuzu/pull/11936
