### ISSUE TITLE
Request: Layout prompts for languages other than English

### ISSUE THREAD

**Issue by Doradorig** [Monkbreh/MHGU-HD-Project#3]
The layout prompts are working really well (I have tried myself the Xbox ones) but the in-game prompts only work while the game language is set to English. I know you have done more than enough and this mod is already amazing, but it would be great if you could include prompts for other languages, I am particularly interested in Spanish. I totally understand if you don't want to make them but it would be great if you could explain how it could be done.

**Comment by SuperLeiyan** [comment]
I'd like to know how it could be done as well, I'm interessted in Chinese.

**Comment by Monkbreh** [comment]
More languages support coming soon, i would have done it sooner but sadly am very busy these days.

**Comment by SuperLeiyan** [comment]
Awesome news, really looking forward to it!

**Comment by SuperLeiyan** [comment]
Any updates on this?

**Comment by Monkbreh** [comment]
yes ive picked up on resuming other languages support, will be released soon
