### ISSUE TITLE
Incorrect disarm trap buttom on English Xbox UI

### ISSUE THREAD

**Issue by F4CELES5** [Monkbreh/MHGU-HD-Project#4]
Man, I know it is a really really small issue, but the english Xbox UI is showing the wrong buttom when you are above a trap to disarm it.
It shows the start buttom not the select. I dont know if it happens on the other languages.

Thanks for this texture pack, your work is really amazing.

**Comment by Monkbreh** [comment]
Thanks for pointing that out will get it fixed next update !

**Comment by Monkbreh** [comment]
.
