### ISSUE TITLE
Mod is detected on Yuzu but doesn't actually do anything

### ISSUE THREAD

**Issue by docctm** [Monkbreh/MHGU-HD-Project#5]
I'm using english nintendo layout if that matters,

Followed the directions provided, path is (yuzu\load\0100770008DD8000\(NEW FOLDER)) 

I've tried just about everything I could think of including:
-renaming New folder to MHGU HD Project (with and without spaces)
-naming the mod folder to something else entirely
-making a new folder both inside and outside the mod directory to put the romfs file in
-going into New Folder and creating another New Folder to put the romfs in, (both folders were subject to name testing)
-renaming the romfs folder to cheats (it was still detected but produced the same result of doing nothing)
-tried running it in OpenGL instead of Vulkan
-also messed around with the other bottom options like turning accuracy to normal instead of high, testing the upscalers, docked vs undocked, etc.
-also reinstalling/re extracting the file a few times (in different locations) 

--also all of these were tested after disabling and re-enabling the mod between attempts just to be absolutely sure.
--and screenshots were taken of every attempt both in game and on the save file screen just to be 1000 percent sure I didn't miss something.

I'm not sure if 80% of the solutions I tried even do anything, but I wanted to make sure I covered all bases.
Apologies for the long winded ticket.

**Comment by docctm** [comment]
forgot to mention it was the latest version of yuzu as well, my bad.

**Comment by JumpingY** [comment]
> I'm using english nintendo layout if that matters,
> 
> Followed the directions provided, path is (yuzu\load\0100770008DD8000(NEW FOLDER))
> 
> I've tried just about everything I could think of including: -renaming New folder to MHGU HD Project (with and without spaces) -naming the mod folder to something else entirely -making a new folder both inside and outside the mod directory to put the romfs file in -going into New Folder and creating another New Folder to put the romfs in, (both folders were subject to name testing) -renaming the romfs folder to cheats (it was still detected but produced the same result of doing nothing) -tried running it in OpenGL instead of Vulkan -also messed around with the other bottom options like turning accuracy to normal instead of high, testing the upscalers, docked vs undocked, etc. -also reinstalling/re extracting the file a few times (in different locations)
> 
> --also all of these were tested after disabling and re-enabling the mod between attempts just to be absolutely sure. --and screenshots were taken of every attempt both in game and on the save file screen just to be 1000 percent sure I didn't miss something.
> 
> I'm not sure if 80% of the solutions I tried even do anything, but I wanted to make sure I covered all bases. Apologies for the long winded ticket.

update yuzu

**Comment by docctm** [comment]
> > I'm using english nintendo layout if that matters,
> > Followed the directions provided, path is (yuzu\load\0100770008DD8000(NEW FOLDER))
> > I've tried just about everything I could think of including: -renaming New folder to MHGU HD Project (with and without spaces) -naming the mod folder to something else entirely -making a new folder both inside and outside the mod directory to put the romfs file in -going into New Folder and creating another New Folder to put the romfs in, (both folders were subject to name testing) -renaming the romfs folder to cheats (it was still detected but produced the same result of doing nothing) -tried running it in OpenGL instead of Vulkan -also messed around with the other bottom options like turning accuracy to normal instead of high, testing the upscalers, docked vs undocked, etc. -also reinstalling/re extracting the file a few times (in different locations)
> > --also all of these were tested after disabling and re-enabling the mod between attempts just to be absolutely sure. --and screenshots were taken of every attempt both in game and on the save file screen just to be 1000 percent sure I didn't miss something.
> > I'm not sure if 80% of the solutions I tried even do anything, but I wanted to make sure I covered all bases. Apologies for the long winded ticket.
> 
> update yuzu

I went on the site and got the build from yesterday just to be absolutely sure. no luck so far ):

**Comment by Monkbreh** [comment]
Make sure you have GU updated to v1.4.0, and avoid using the early access version for yuzu.  Your path should be like this -\AppData\Roaming\yuzu\load\0100770008DD8000\Folder\romfs\nativeNX. If all fails you can still switch to ryujinx.

**Comment by docctm** [comment]
> Make sure you have GU updated to v1.4.0, and avoid using the early access version for yuzu. Your path should be like this -\AppData\Roaming\yuzu\load\0100770008DD8000\Folder\romfs\nativeNX. If all fails you can still switch to ryujinx.

somehow just fixed itself in a random update. thank you for the assistance anyways though. + sorry for wasting your time
