### ISSUE TITLE
Meownster Hunters charging bar showing artifact

### ISSUE THREAD

**Issue by Nackha1** [Monkbreh/MHGU-HD-Project#6]
As one can see from the following image, there is a thin _(~1px)_ vertical line at the **left** of the charging bar in the Meownster Hunters minigame.
This vertical line follows the color of the charge meter, so I think there some issue with the **texture sizes** or some kind of **missalignment**.

![image](https://github.com/Monkbreh/MHGU-HD-Project/assets/47718457/9fdd4033-117b-45f7-8d34-2cfeaa302901)

**EDIT**: I'm currently running MHGU on Yuzu 1676

**Comment by Monkbreh** [comment]
yeah the texture is outside the gui boundary will get it fixed next ver

**Comment by Monkbreh** [comment]
Seems like the issue stems from increasing the native game resolution, in some cases increasing the native res can break the UI.
