### ISSUE TITLE
Inappropriate Hellblade Glavenus armors texture effects 

### ISSUE THREAD

**Issue by JumpingY** [Monkbreh/MHGU-HD-Project#8]
It looks like it's caused by alpha channel issue with HD textures

**Comment by Monkbreh** [comment]
Can you screenshot the difference, it would help. Thanks

**Comment by JumpingY** [comment]
> Can you screenshot the difference, it would help. Thanks

![00](https://github.com/Monkbreh/MHGU-HD-Project/assets/54348327/0480362b-6996-4775-a5b1-72b1f85d1517)

**Comment by Monkbreh** [comment]
updated
